# Generated by Django 4.1.6 on 2023-03-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_restaurante_exp', models.CharField(max_length=60)),
                ('nombre_foodie', models.CharField(max_length=30)),
                ('apellido_foodie', models.CharField(max_length=30)),
                ('email_foodie', models.EmailField(max_length=254)),
                ('fecha_experiencia', models.DateField(default='00/00/0000')),
                ('calificación_experiencia', models.IntegerField()),
                ('comentarios_experiencia', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_restaurante', models.CharField(max_length=60)),
                ('direccion_calle', models.CharField(max_length=60)),
                ('direccion_altura', models.IntegerField()),
                ('direccion_ciudad', models.CharField(max_length=60)),
                ('fecha_inicio_act', models.DateField(default='00/00/0000')),
                ('tipo_restaurante', models.CharField(max_length=60)),
            ],
        ),
    ]
